"""initial_complete_schema

Revision ID: df9272d3b653
Revises:
Create Date: 2026-04-08 12:33:04.503825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'df9272d3b653'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_code'), 'achievements', ['code'], unique=True)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('activities',
    sa.Column('user_entity_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_action_type'), 'activities', ['action_type'], unique=False)
    op.create_index(op.f('ix_activities_entity_id'), 'activities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_is_current'), 'activities', ['is_current'], unique=False)
    op.create_index(op.f('ix_activities_user_entity_id'), 'activities', ['user_entity_id'], unique=False)
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('reward_xp', sa.Integer(), nullable=False),
    sa.Column('reward_achievement', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_code'), 'challenges', ['code'], unique=True)
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('comments',
    sa.Column('problem_entity_id', sa.Integer(), nullable=False),
    sa.Column('author_entity_id', sa.Integer(), nullable=False),
    sa.Column('parent_entity_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('comment_type', sa.String(length=50), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=True),
    sa.Column('flag_reason', sa.String(length=200), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_author_entity_id'), 'comments', ['author_entity_id'], unique=False)
    op.create_index(op.f('ix_comments_entity_id'), 'comments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_is_current'), 'comments', ['is_current'], unique=False)
    op.create_index(op.f('ix_comments_problem_entity_id'), 'comments', ['problem_entity_id'], unique=False)
    op.create_table('donations',
    sa.Column('fundraising_entity_id', sa.Integer(), nullable=False),
    sa.Column('donor_entity_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_anonymous', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donations_entity_id'), 'donations', ['entity_id'], unique=False)
    op.create_index(op.f('ix_donations_fundraising_entity_id'), 'donations', ['fundraising_entity_id'], unique=False)
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_index(op.f('ix_donations_is_current'), 'donations', ['is_current'], unique=False)
    op.create_table('follows',
    sa.Column('follower_entity_id', sa.Integer(), nullable=False),
    sa.Column('following_entity_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follows_entity_id'), 'follows', ['entity_id'], unique=False)
    op.create_index(op.f('ix_follows_follower_entity_id'), 'follows', ['follower_entity_id'], unique=False)
    op.create_index(op.f('ix_follows_following_entity_id'), 'follows', ['following_entity_id'], unique=False)
    op.create_index(op.f('ix_follows_id'), 'follows', ['id'], unique=False)
    op.create_index(op.f('ix_follows_is_current'), 'follows', ['is_current'], unique=False)
    op.create_table('fundraising_expenses',
    sa.Column('fundraising_entity_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('approved_by_entity_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundraising_expenses_entity_id'), 'fundraising_expenses', ['entity_id'], unique=False)
    op.create_index(op.f('ix_fundraising_expenses_fundraising_entity_id'), 'fundraising_expenses', ['fundraising_entity_id'], unique=False)
    op.create_index(op.f('ix_fundraising_expenses_id'), 'fundraising_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_fundraising_expenses_is_current'), 'fundraising_expenses', ['is_current'], unique=False)
    op.create_table('fundraisings',
    sa.Column('problem_entity_id', sa.Integer(), nullable=False),
    sa.Column('goal_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundraisings_entity_id'), 'fundraisings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_fundraisings_id'), 'fundraisings', ['id'], unique=False)
    op.create_index(op.f('ix_fundraisings_is_current'), 'fundraisings', ['is_current'], unique=False)
    op.create_index(op.f('ix_fundraisings_problem_entity_id'), 'fundraisings', ['problem_entity_id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_entity_id', sa.Integer(), nullable=False),
    sa.Column('notification_type', sa.Enum('PROBLEM_STATUS_CHANGED', 'PROBLEM_ASSIGNED', 'PROBLEM_COMMENTED', 'COMMENT_REPLIED', 'PROBLEM_UPVOTED', 'PROBLEM_VERIFIED', 'PROBLEM_REJECTED', 'COMMENT_HIDDEN', 'USER_MENTIONED', 'PROBLEM_SUBSCRIBED', name='notificationtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('problem_entity_id', sa.Integer(), nullable=True),
    sa.Column('comment_entity_id', sa.Integer(), nullable=True),
    sa.Column('actor_entity_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_comment_entity_id'), 'notifications', ['comment_entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_entity_id'), 'notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_current'), 'notifications', ['is_current'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_problem_entity_id'), 'notifications', ['problem_entity_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_entity_id'), 'notifications', ['user_entity_id'], unique=False)
    op.create_table('problem_media',
    sa.Column('problem_entity_id', sa.Integer(), nullable=False),
    sa.Column('uploader_entity_id', sa.Integer(), nullable=False),
    sa.Column('media_type', sa.Enum('photo', 'video', name='mediatype'), nullable=False),
    sa.Column('media_category', sa.Enum('problem', 'in_progress', 'result', name='mediacategory'), nullable=True),
    sa.Column('status', sa.Enum('active', 'removed', 'replaced', name='mediastatus'), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('video_width', sa.Integer(), nullable=True),
    sa.Column('video_height', sa.Integer(), nullable=True),
    sa.Column('is_processed', sa.Integer(), nullable=True),
    sa.Column('hls_url', sa.String(length=500), nullable=True),
    sa.Column('exif_lat', sa.Float(), nullable=True),
    sa.Column('exif_lon', sa.Float(), nullable=True),
    sa.Column('exif_taken_at', sa.DateTime(), nullable=True),
    sa.Column('ai_tags', sa.String(length=500), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('ai_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problem_media_entity_id'), 'problem_media', ['entity_id'], unique=False)
    op.create_index(op.f('ix_problem_media_id'), 'problem_media', ['id'], unique=False)
    op.create_index(op.f('ix_problem_media_is_current'), 'problem_media', ['is_current'], unique=False)
    op.create_index(op.f('ix_problem_media_problem_entity_id'), 'problem_media', ['problem_entity_id'], unique=False)
    op.create_table('problems',
    sa.Column('author_entity_id', sa.Integer(), nullable=False),
    sa.Column('zone_entity_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('location', geoalchemy2.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('problem_type', sa.Enum('pothole', 'garbage', 'road_work', 'pollution', 'traffic_light', 'flooding', 'lighting', 'construction', 'roads', 'infrastructure', 'other', name='problemtype'), nullable=False),
    sa.Column('nature', sa.Enum('temporary', 'permanent', name='problemnature'), nullable=False),
    sa.Column('status', sa.Enum('open', 'in_progress', 'solved', 'rejected', 'archived', name='problemstatus'), nullable=True),
    sa.Column('resolved_by_entity_id', sa.Integer(), nullable=True),
    sa.Column('resolver_type', sa.Enum('volunteer', 'official_org', 'auto_resolved', name='resolvertype'), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('truth_score', sa.Float(), nullable=True),
    sa.Column('urgency_score', sa.Float(), nullable=True),
    sa.Column('impact_score', sa.Float(), nullable=True),
    sa.Column('inconvenience_score', sa.Float(), nullable=True),
    sa.Column('priority_score', sa.Float(), nullable=True),
    sa.Column('vote_count', sa.Integer(), nullable=True),
    sa.Column('comment_count', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('ai_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_problems_author_entity_id'), 'problems', ['author_entity_id'], unique=False)
    op.create_index(op.f('ix_problems_entity_id'), 'problems', ['entity_id'], unique=False)
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.create_index(op.f('ix_problems_is_current'), 'problems', ['is_current'], unique=False)
    op.create_index(op.f('ix_problems_zone_entity_id'), 'problems', ['zone_entity_id'], unique=False)
    op.create_table('reports',
    sa.Column('reporter_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('resolved_by_entity_id', sa.Integer(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_entity_id'), 'reports', ['entity_id'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_is_current'), 'reports', ['is_current'], unique=False)
    op.create_index(op.f('ix_reports_reporter_entity_id'), 'reports', ['reporter_entity_id'], unique=False)
    op.create_table('reputation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_entity_id', sa.Integer(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('related_problem_entity_id', sa.Integer(), nullable=True),
    sa.Column('related_vote_entity_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_reputation', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_logs_id'), 'reputation_logs', ['id'], unique=False)
    op.create_index(op.f('ix_reputation_logs_user_entity_id'), 'reputation_logs', ['user_entity_id'], unique=False)
    op.create_table('simulation_events',
    sa.Column('zone_entity_id', sa.Integer(), nullable=False),
    sa.Column('created_by_entity_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('road_repair', 'new_construction', 'demolition', 'flood_risk', 'pollution_source', 'traffic_change', 'infrastructure_upgrade', name='simeventtype'), nullable=False),
    sa.Column('status', sa.Enum('planned', 'active', 'completed', 'cancelled', name='simeventstatus'), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_area', geoalchemy2.Geometry(srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('planned_start', sa.DateTime(), nullable=True),
    sa.Column('planned_end', sa.DateTime(), nullable=True),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('traffic_impact', sa.Float(), nullable=True),
    sa.Column('pollution_impact', sa.Float(), nullable=True),
    sa.Column('risk_delta', sa.Float(), nullable=True),
    sa.Column('simulation_params', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_simulation_events_entity_id'), 'simulation_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_simulation_events_id'), 'simulation_events', ['id'], unique=False)
    op.create_index(op.f('ix_simulation_events_is_current'), 'simulation_events', ['is_current'], unique=False)
    op.create_index(op.f('ix_simulation_events_zone_entity_id'), 'simulation_events', ['zone_entity_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('user_entity_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_entity_id', sa.Integer(), nullable=False),
    sa.Column('notification_types', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_entity_id'), 'subscriptions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_is_current'), 'subscriptions', ['is_current'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_entity_id'), 'subscriptions', ['user_entity_id'], unique=False)
    op.create_table('user_achievements',
    sa.Column('user_entity_id', sa.Integer(), nullable=False),
    sa.Column('achievement_code', sa.String(length=50), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_achievement_code'), 'user_achievements', ['achievement_code'], unique=False)
    op.create_index(op.f('ix_user_achievements_entity_id'), 'user_achievements', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_achievements_is_current'), 'user_achievements', ['is_current'], unique=False)
    op.create_index(op.f('ix_user_achievements_user_entity_id'), 'user_achievements', ['user_entity_id'], unique=False)
    op.create_table('user_challenges',
    sa.Column('user_entity_id', sa.Integer(), nullable=False),
    sa.Column('challenge_code', sa.String(length=50), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=False),
    sa.Column('completed', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_challenges_challenge_code'), 'user_challenges', ['challenge_code'], unique=False)
    op.create_index(op.f('ix_user_challenges_entity_id'), 'user_challenges', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_challenges_id'), 'user_challenges', ['id'], unique=False)
    op.create_index(op.f('ix_user_challenges_is_current'), 'user_challenges', ['is_current'], unique=False)
    op.create_index(op.f('ix_user_challenges_user_entity_id'), 'user_challenges', ['user_entity_id'], unique=False)
    op.create_table('user_levels',
    sa.Column('user_entity_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('next_level_xp', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_levels_entity_id'), 'user_levels', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_levels_id'), 'user_levels', ['id'], unique=False)
    op.create_index(op.f('ix_user_levels_is_current'), 'user_levels', ['is_current'], unique=False)
    op.create_index(op.f('ix_user_levels_user_entity_id'), 'user_levels', ['user_entity_id'], unique=False)
    op.create_table('user_notification_settings',
    sa.Column('user_entity_id', sa.Integer(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_on_comment', sa.Boolean(), nullable=False),
    sa.Column('email_on_status_change', sa.Boolean(), nullable=False),
    sa.Column('email_on_official_response', sa.Boolean(), nullable=False),
    sa.Column('email_on_problem_solved', sa.Boolean(), nullable=False),
    sa.Column('email_on_mention', sa.Boolean(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_on_comment', sa.Boolean(), nullable=False),
    sa.Column('push_on_status_change', sa.Boolean(), nullable=False),
    sa.Column('digest_enabled', sa.Boolean(), nullable=False),
    sa.Column('digest_frequency', sa.String(length=20), nullable=False),
    sa.Column('digest_day', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Integer(), nullable=True),
    sa.Column('quiet_hours_end', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notification_settings_entity_id'), 'user_notification_settings', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_notification_settings_id'), 'user_notification_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_notification_settings_is_current'), 'user_notification_settings', ['is_current'], unique=False)
    op.create_index(op.f('ix_user_notification_settings_user_entity_id'), 'user_notification_settings', ['user_entity_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_entity_id', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_entity_id'), 'user_profiles', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_is_current'), 'user_profiles', ['is_current'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_entity_id'), 'user_profiles', ['user_entity_id'], unique=False)
    op.create_table('users',
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('user', 'moderator', 'admin', 'official', 'volunteer', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deactivated', name='userstatus'), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('ban_reason', sa.Text(), nullable=True),
    sa.Column('ban_until', sa.DateTime(), nullable=True),
    sa.Column('banned_by_entity_id', sa.Integer(), nullable=True),
    sa.Column('banned_at', sa.DateTime(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('backup_codes', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_entity_id'), 'users', ['entity_id'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_is_current'), 'users', ['is_current'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('votes',
    sa.Column('problem_entity_id', sa.Integer(), nullable=False),
    sa.Column('user_entity_id', sa.Integer(), nullable=False),
    sa.Column('is_true', sa.Boolean(), nullable=True),
    sa.Column('urgency', sa.Integer(), nullable=True),
    sa.Column('impact', sa.Integer(), nullable=True),
    sa.Column('inconvenience', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('problem_entity_id', 'user_entity_id', 'is_current', name='uq_vote_current')
    )
    op.create_index(op.f('ix_votes_entity_id'), 'votes', ['entity_id'], unique=False)
    op.create_index(op.f('ix_votes_id'), 'votes', ['id'], unique=False)
    op.create_index(op.f('ix_votes_is_current'), 'votes', ['is_current'], unique=False)
    op.create_index(op.f('ix_votes_problem_entity_id'), 'votes', ['problem_entity_id'], unique=False)
    op.create_index(op.f('ix_votes_user_entity_id'), 'votes', ['user_entity_id'], unique=False)
    op.create_table('zones',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('zone_type', sa.String(length=50), nullable=False),
    sa.Column('parent_entity_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('boundary', geoalchemy2.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('center_lat', sa.Float(), nullable=True),
    sa.Column('center_lon', sa.Float(), nullable=True),
    sa.Column('total_problems', sa.Integer(), nullable=True),
    sa.Column('open_problems', sa.Integer(), nullable=True),
    sa.Column('solved_problems', sa.Integer(), nullable=True),
    sa.Column('pollution_index', sa.Float(), nullable=True),
    sa.Column('traffic_index', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.Column('change_reason', sa.String(length=300), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_entity_id'), 'zones', ['entity_id'], unique=False)
    op.create_index(op.f('ix_zones_id'), 'zones', ['id'], unique=False)
    op.create_index(op.f('ix_zones_is_current'), 'zones', ['is_current'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zones_is_current'), table_name='zones')
    op.drop_index(op.f('ix_zones_id'), table_name='zones')
    op.drop_index(op.f('ix_zones_entity_id'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_votes_user_entity_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_problem_entity_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_is_current'), table_name='votes')
    op.drop_index(op.f('ix_votes_id'), table_name='votes')
    op.drop_index(op.f('ix_votes_entity_id'), table_name='votes')
    op.drop_table('votes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_is_current'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_entity_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_profiles_user_entity_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_is_current'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_entity_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_notification_settings_user_entity_id'), table_name='user_notification_settings')
    op.drop_index(op.f('ix_user_notification_settings_is_current'), table_name='user_notification_settings')
    op.drop_index(op.f('ix_user_notification_settings_id'), table_name='user_notification_settings')
    op.drop_index(op.f('ix_user_notification_settings_entity_id'), table_name='user_notification_settings')
    op.drop_table('user_notification_settings')
    op.drop_index(op.f('ix_user_levels_user_entity_id'), table_name='user_levels')
    op.drop_index(op.f('ix_user_levels_is_current'), table_name='user_levels')
    op.drop_index(op.f('ix_user_levels_id'), table_name='user_levels')
    op.drop_index(op.f('ix_user_levels_entity_id'), table_name='user_levels')
    op.drop_table('user_levels')
    op.drop_index(op.f('ix_user_challenges_user_entity_id'), table_name='user_challenges')
    op.drop_index(op.f('ix_user_challenges_is_current'), table_name='user_challenges')
    op.drop_index(op.f('ix_user_challenges_id'), table_name='user_challenges')
    op.drop_index(op.f('ix_user_challenges_entity_id'), table_name='user_challenges')
    op.drop_index(op.f('ix_user_challenges_challenge_code'), table_name='user_challenges')
    op.drop_table('user_challenges')
    op.drop_index(op.f('ix_user_achievements_user_entity_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_is_current'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_entity_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_code'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_subscriptions_user_entity_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_is_current'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_entity_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_simulation_events_zone_entity_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_is_current'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_id'), table_name='simulation_events')
    op.drop_index(op.f('ix_simulation_events_entity_id'), table_name='simulation_events')
    op.drop_table('simulation_events')
    op.drop_index(op.f('ix_reputation_logs_user_entity_id'), table_name='reputation_logs')
    op.drop_index(op.f('ix_reputation_logs_id'), table_name='reputation_logs')
    op.drop_table('reputation_logs')
    op.drop_index(op.f('ix_reports_reporter_entity_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_is_current'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_entity_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_problems_zone_entity_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_is_current'), table_name='problems')
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_entity_id'), table_name='problems')
    op.drop_index(op.f('ix_problems_author_entity_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_problem_media_problem_entity_id'), table_name='problem_media')
    op.drop_index(op.f('ix_problem_media_is_current'), table_name='problem_media')
    op.drop_index(op.f('ix_problem_media_id'), table_name='problem_media')
    op.drop_index(op.f('ix_problem_media_entity_id'), table_name='problem_media')
    op.drop_table('problem_media')
    op.drop_index(op.f('ix_notifications_user_entity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_problem_entity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_current'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_entity_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_comment_entity_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_fundraisings_problem_entity_id'), table_name='fundraisings')
    op.drop_index(op.f('ix_fundraisings_is_current'), table_name='fundraisings')
    op.drop_index(op.f('ix_fundraisings_id'), table_name='fundraisings')
    op.drop_index(op.f('ix_fundraisings_entity_id'), table_name='fundraisings')
    op.drop_table('fundraisings')
    op.drop_index(op.f('ix_fundraising_expenses_is_current'), table_name='fundraising_expenses')
    op.drop_index(op.f('ix_fundraising_expenses_id'), table_name='fundraising_expenses')
    op.drop_index(op.f('ix_fundraising_expenses_fundraising_entity_id'), table_name='fundraising_expenses')
    op.drop_index(op.f('ix_fundraising_expenses_entity_id'), table_name='fundraising_expenses')
    op.drop_table('fundraising_expenses')
    op.drop_index(op.f('ix_follows_is_current'), table_name='follows')
    op.drop_index(op.f('ix_follows_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_following_entity_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_follower_entity_id'), table_name='follows')
    op.drop_index(op.f('ix_follows_entity_id'), table_name='follows')
    op.drop_table('follows')
    op.drop_index(op.f('ix_donations_is_current'), table_name='donations')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_fundraising_entity_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_entity_id'), table_name='donations')
    op.drop_table('donations')
    op.drop_index(op.f('ix_comments_problem_entity_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_is_current'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_entity_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_author_entity_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_code'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_activities_user_entity_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_is_current'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_entity_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_action_type'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_code'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###
